### ISSUE TITLE
Borm CI is broken on main

### ISSUE THREAD

**Issue by FreddyFox892** [Hochfrequenz/bo4e-python-orm#129]
Hi @DeltaDaniel @lord-haffi ,

igendwo ist das Borm gebochen, da alle PR, selbst mit nur einer Readme änderung https://github.com/Hochfrequenz/bo4e-python-orm/pull/128 Failen.
Bitte einmal fixen, da ich nicht tief genug im borm drin stecke um das selbst zu Fixen :)

**Comment by lord-haffi** [comment]
Das Thema hatten wir doch letztens, mein ich. In der tox.ini ist ein docker-compose Befehl, der raus muss. Stattdessen sollte das in den Workflow files aufgerufen werden per `docker compose` (**ohne Bindestrich**).

**Comment by DeltaDaniel** [comment]
https://github.com/Hochfrequenz/bo4e-python-orm/pull/133
